[package]
name = "chip8forever"
version = "0.1.0"
authors = ["Micha≈Ç Mieczkowski <mhlmieczkowski@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
